// src/Fuel/CreateFuelTypeDialog.tsx
import { FuelType } from "@/model/DataModel";
import { withLimitConfirmation } from "@/model/LimitUi";
import {
  useFormula,
  useProp,
  exists,
  Box,
  Prop,
  popPage,
  Button,
  Card,
  Field,
  Label,
  NumField,
  Row,
  mdColors,
  Txt,
  pushPage,
} from "miwi";

export const openCreateFuelTypeDialog = (props: {
  onCreate?: (newObject: FuelType) => void;
}) => 
  withLimitConfirmation({
    count: FuelType.limit.count,
    limit: FuelType.limit.max,
    labelSingular: `Fuel Type`,
    labelPlural: `Fuel Types`,
    action: () =>
      pushPage(CreateFuelTypeDialog, props),
  });

function CreateFuelTypeDialog(props: {
  onCreate?: (newObject: FuelType) => void;
}) {
  // Assign prop defaults
  props.onCreate = props.onCreate ?? undefined;

  const name = useProp(``) as Prop<string>;
  const rate = useProp(null) as Prop<number | null>;

  const computedFuelType = useFormula(() => {
    return {
      name: name.value,
      rate: rate.value,
    };
  });

  const fuelTypeIsValid = useFormula(() => {
    return FuelType.isValid(computedFuelType.value);
  });

  function handleYes() {
    if (!fuelTypeIsValid.value) return;
    popPage();
    const newFuelType = FuelType.create({
      ...computedFuelType.value,
      createdPosix: Date.now(),
    });
    if (exists(props.onCreate)) props.onCreate(newFuelType);
  }

  return (
    <Box
      onClick={popPage}
      widthGrows
      heightGrows
      fill="#00000099"
      bonusTouchArea={false}
    >
      <Card width="75%" shadowSize={0} preventClickPropagation>
        <Txt h1>Create Fuel Type</Txt>
        {/* TODO Doest it need autofocus like other cards (for consistency)? */}
        <Label label="Name" widthGrows>
          <Field value={name} hintText="Unnamed" underlined
          capitalize={"words"} keyboard={"text"}/>
        </Label>
        <Label label="Rate" widthGrows>
          <NumField
            negativesAreAllowed={false}
            underlined
            valueSig={rate}
            hint="$/gal."
          />
        </Label>
        <Row widthGrows align={$Align.spaceEvenly}>
          <Button outlined onClick={popPage}>
            Cancel
          </Button>
          <Button
            onClick={handleYes}
            fill={fuelTypeIsValid.value ? mdColors.green : mdColors.grey}
          >
            Create
          </Button>
        </Row>
      </Card>
    </Box>
  );
}

// src/views/settings/CreateFuelType.dialog.vue
<script setup lang="ts">
// import { PropType } from "vue";
import { pageTransitions, popPage, pushPage } from "@/Nav";
import { getAppData, isFuelTypeValid } from "@/AppData";
import { PropType, VNodeRef, computed, ref } from "vue";
import { TankShapeId } from "@/views/tanks/ShapeUtils";
import { exists } from "@/utils";

const props = defineProps({});

const appData = getAppData();

const cardRef = ref<VNodeRef | null>(null);
const name = ref<string>(``);
const rate = ref<number | null>(null);
const computedFuelType = computed(() => ({
  name: name.value,
  rate: rate.value,
}));
const fuelTypeIsValid = computed(() => {
  return isFuelTypeValid(computedFuelType.value);
});

function closePopUp() {
  popPage();
}

function handleYes() {
  if (!fuelTypeIsValid.value) return;
  closePopUp();
  appData.fuelTypes.add(computedFuelType.value);
}

// Close the pop up when the user clicks outside of it
function popOnClickOutside(e: MouseEvent) {
  if (!cardRef.value?.$el.contains(e.target)) {
    closePopUp();
    e.stopPropagation();
  }
}
</script>

<script lang="ts">
export default {
  transitions: pageTransitions.fadeIn(),
};
</script>

<template>
  <Box
    :onClick="popOnClickOutside"
    :sty="{
      width: `1f`,
      height: `1f`,
      background: `#00000099`,
    }"
  >
    <Card
      ref="cardRef"
      :sty="{
        width: `75%`,
        shadowSize: 0,
      }"
    >
      <Text title>Create Fuel Type</Text>
      <Label
        label="Name"
        :sty="{
          width: `1f`,
        }"
      >
        <Field v-model:value="name" underlined hint="Unnamed" />
      </Label>
      <Label
        label="Rate"
        :sty="{
          width: `1f`,
        }"
      >
        <NumField
          :negativesAreAllowed="false"
          underlined
          v-model:value="rate"
          hint="$/gal."
        />
      </Label>
      <Row :sty="{ width: `1f`, align: $Align.spaceEvenly }">
        <Button outlined :onClick="closePopUp">Cancel</Button>
        <Button
          :onClick="handleYes"
          :sty="{
            background: fuelTypeIsValid ? $mdColors.green : $mdColors.grey,
          }"
          >Create</Button
        >
      </Row>
    </Card>
  </Box>
</template>
