// src/views/settings/FuelTypeEntry.vue
<script setup lang="ts">
import { defineProps, PropType } from "vue";
import { FuelType } from "@/AppData";
import { pushPage } from "@/Nav";
import DeleteDialogVue from "../components/DeleteDialog.vue";
// Allow overriding of the default sty
const props = defineProps({
  sty: {
    type: Object as PropType<Partial<Sty>>,
    default: {},
  },
  fuelType: {
    type: Object as PropType<FuelType>,
    required: true,
  },
});

function deletePressed() {
  pushPage(DeleteDialogVue, {
    obj: props.fuelType,
    message: `Are you sure you want to permanently delete "${
      props.fuelType.name ?? `this fuel type`
    }"? Associated tanks will have their fuel type set to "None".`,
  });
}
</script>

<template>
  <Row
    v-if="fuelType.isLoaded"
    :sty="{
      padBetween: 1,
    }"
  >
    <Label
      label="Name"
      :sty="{
        width: `4f`,
      }"
    >
      <Field v-model:value="fuelType.name" underlined hint="Unnamed" />
    </Label>
    <Label
      label="Rate"
      :sty="{
        width: `3f`,
      }"
    >
      <NumField
        :negativesAreAllowed="false"
        underlined
        v-model:value="fuelType.rate"
        hint="$/gal."
      />
    </Label>
    <DeleteOptionsButton @delete="deletePressed" />
  </Row>
  <Text v-else hint :sty="{ width: `1f` }">Loading...</Text>
</template>

// src/Fuel/FuelTypeEntry.tsx
import DeleteDialog from "@/components/DeleteDialog";
import { Field, HiddenDelete, NumField, Row, pushPage, useFormula } from "miwi";
import { FuelType } from "@/model/DataModel";
import {HiddenOptions} from "@/components/HiddenOptions";
import {Flag} from "mufasa/dist/Utils";

export default function FuelTypeEntry(props: { fuelType: FuelType }) {
  function deletePressed() {
    pushPage(DeleteDialog, {
      obj: props.fuelType,
      message: `Are you sure you want to permanently delete "${
        props.fuelType.name ?? `this fuel type`
      }"? Associated tanks will have their fuel type set to "None".`,
    });
  }

  return (
    <Row widthGrows padBetween={1} alignLeft>
      <Field
        value={useFormula(
          () => props.fuelType.name ?? ``,
          (v) => (props.fuelType.name = v),
        )}
        underlined
        hintText="Unnamed"
      />
      <NumField
        negativesAreAllowed={false}
        underlined
        valueSig={useFormula(
          () => (props.fuelType.rate ?? 0) == 0 ? null : props.fuelType.rate,
          (v) => props.fuelType.rate = v,
        )}
        hint="$/gal."
        align={$Align.centerLeft}
        width={5}
      />
      <HiddenOptions showIcons onDelete={deletePressed} />
    </Row>
  );
}
