// src/Clients/ClientEntry.tsx
import {
  Row,
  Txt,
  pushPage,
  useProp,
  mdColors,
  HiddenOption,
  HiddenOptions,
  DeleteOption,
  theme,
} from "miwi";
import DeleteDialog from "../components/DeleteDialog";
import { isClientValid, getClientLabel } from "@/AppData";
import ClientPage from "./ClientPage";
import { Client } from "./Client";
import { mdiTankerTruck } from "@mdi/js";
import { openCreateClientDialog } from "@/Deliveries/CreateDeliveryDialog";
import { DeliveryPage } from "@/Deliveries/DeliveryPage";

export default function ClientEntery(props: { client: Client }) {
  function deletePressed() {
    pushPage(DeleteDialog, {
      obj: props.client,
      message: `Are you sure you want to permanently delete "${
        props.client.clientId ?? ``
      }${props.client.clientId && props.client.name ? ` - ` : ``}${
        props.client.name ?? ``
      }"?`,
    });
  }

  let myTextColor = useProp<string>(mdColors.black);

  function clicked() {
    myTextColor.value = mdColors.green;
    setTimeout(() => (myTextColor.value = mdColors.black), 250);
    setTimeout(() => pushPage(ClientPage, { client: props.client }), 17);
  }

  return (
    <Row
      onClick={clicked}
      widthGrows
      height={1}
      spaceBetween
      stroke={myTextColor.value}
    >
      <Txt
        widthGrows
        singleLine
        stroke={isClientValid(props.client) ? myTextColor.value : mdColors.grey}
      >
        {getClientLabel(props.client)}
      </Txt>
      <HiddenOptions
        cancelOptions={{
          stroke: theme.palette.hint,
        }}
      >
        <HiddenOption
          text={`Delivery`}
          icon={mdiTankerTruck}
          onClick={() =>
            openCreateClientDialog({
              onCreate: (delivery) => {
                pushPage(DeliveryPage, { delivery });
              },
              setClient: props.client,
            })
          }
        />
        <DeleteOption onClick={deletePressed} />
      </HiddenOptions>
    </Row>
  );
}

// src/views/clients/ClientEntry.vue
<script setup lang="ts">
import { PropType, VNodeRef, defineProps, ref } from "vue";
import { pushPage } from "@/Nav";
import ClientPage from "./Client.page.vue";
import { Client, isClientValid, getClientLabel } from "@/AppData";
import { mdColors } from "@/miwi-md/Box/BoxDecoration";
import DeleteDialog from "../components/DeleteDialog.vue";

// Create a prop called size
const props = defineProps({
  client: {
    type: Object as PropType<Client>,
    required: true,
  },
});

function deletePressed() {
  pushPage(DeleteDialog, {
    obj: props.client,
    message: `Are you sure you want to permanently delete "${
      props.client.clientId ?? ``
    } ${props.client.clientId && props.client.name ? ` - ` : ``} ${
      props.client.name ?? ``
    }"?`,
  });
}

function clicked() {
  pushPage(ClientPage, { client: props.client });
}
</script>

<template>
  <Box
    :onClick="clicked"
    :sty="{
      width: `1f`,
      height: 1,
      axis: $Axis.row,
      align: $Align.spaceBetween,
      textColor: client.isLoaded ? mdColors.black : mdColors.grey,
    }"
  >
    <Text
      :sty="{
        width: `1f`,
        overflowX: $Overflow.crop,
        textColor: isClientValid(client) ? mdColors.black : mdColors.grey,
      }"
    >
      {{ client.isLoaded ? getClientLabel(client) : `Loading...` }}
    </Text>
    <DeleteOptionsButton @delete="deletePressed" />
  </Box>
</template>
