// src/Clients/ClientPage.tsx
import { For, createEffect } from "solid-js";
import { listTanks } from "@/AppData";
import {
  AppBar,
  Body,
  Box,
  Column,
  FloatSort,
  HiddenDelete,
  Icon,
  Page,
  Row,
  SortableColumn,
  Txt,
  mdColors,
  popPage,
  useFormula,
  pushPage,
  useNav,
  exists,
  Card,
} from "miwi";
import { mdiCog, mdiDotsVertical, mdiPlus } from "@mdi/js";
import { ClientFields } from "./ClientFields";
import { SettingsPage } from "@/settings/SettingsPage";
import CreateTankDialog from "@/Tanks/CreateTankDialog";
import DeleteDialog from "@/components/DeleteDialog";
import { TankCard } from "@/Tanks/TankCard";
import { CallAndMapButtons } from "./CallAndMapToButtons";
import { Delivery } from "@/Deliveries/Delivery";
import { DeliveryCard } from "@/Deliveries/DeliveryCard";
import { Client } from "./Client";

export default function ClientPage(props: { client: Client }) {
  createEffect(() => {
    if (props.client.isDeleted) {
      popPage();
    }
  });

  const nav = useNav();

  const sortedTanks = useFormula(() => listTanks(props.client.tanks));
  const relatedDeliveries = useFormula(() =>
    Delivery.completedDeliveriesForAllUsers.filter(
      (delivery) =>
        exists(delivery.selectedKnownClient?.docId) &&
        exists(props.client.docId) &&
        delivery.selectedKnownClient.docId === props.client.docId,
    ),
  );

  function deletePressed() {
    pushPage(DeleteDialog, {
      obj: props.client,
      message: `Are you sure you want to permanently delete "${
        props.client.clientId ?? ``
      } ${props.client.clientId && props.client.name ? ` - ` : ``} ${
        props.client.name ?? ``
      }"?`,
    });
  }

  return (
    <Page>
      <AppBar
        shadowSize={1.25}
        right={
          <Icon
            iconPath={mdiCog}
            onClick={() => {
              nav.pushPage(SettingsPage, {});
            }}
          />
        }
      >
        {/* Client Info */}
        <Txt h1>Edit Client</Txt>
      </AppBar>
      <Body padBetween={0.5}>
        <Row widthGrows alignX={$Align.spaceBetween} alignY={$Align.start}>
          <Icon iconPath={mdiDotsVertical} stroke={mdColors.transparent} />
          <Txt h2>Client Info</Txt>
          <HiddenDelete onDelete={deletePressed} />
        </Row>
        <Card>
          <ClientFields
            name={useFormula(
              () => props.client.name ?? ``,
              (val) => (props.client.name = val),
            )}
            clientId={useFormula(
              () => props.client.clientId ?? ``,
              (val) => (props.client.clientId = val),
            )}
            phoneNumber={useFormula(
              () => props.client.phoneNumber ?? ``,

              (val) => (props.client.phoneNumber = val),
            )}
            address={useFormula(
              () => props.client.address ?? ``,
              (val) => (props.client.address = val),
            )}
            notes={useFormula(
              () => props.client.notes ?? ``,
              (val) => (props.client.notes = val),
            )}
          />

          <CallAndMapButtons
            phoneNumber={props.client.phoneNumber}
            address={props.client.address}
          />
        </Card>

        <Box height={1} />

        {/* Tanks */}
        <Row widthGrows alignX={$Align.spaceBetween}>
          <Box width={1.75} />
          <Txt h2>Tanks</Txt>
          <Box width={1.75} alignCenterLeft>
            <Icon
              iconPath={mdiPlus}
              scale={1.25}
              onClick={() =>
                pushPage(CreateTankDialog, { client: props.client })
              }
            />
          </Box>
        </Row>
        <Column padBetween={1}>
          <SortableColumn
            onSort={(props) =>
              FloatSort.moveItem({
                sortedList: sortedTanks.value,
                fromIndex: props.from,
                toIndex: props.to,
                getPos: (tank) => tank.sortPos!,
                setPos: (tank, pos) => (tank.sortPos = pos),
              })
            }
          >
            <For
              each={sortedTanks.value}
              fallback={<Txt hint>Tap + to add tanks.</Txt>}
            >
              {(tank) => <TankCard tank={tank} client={props.client} />}
            </For>
          </SortableColumn>
        </Column>

        <Box height={1} />
        <Row widthGrows alignX={$Align.spaceBetween}>
          <Box width={1.75} />
          <Txt h2>Related Deliveries</Txt>
          <Box width={1.75} alignCenterLeft>
            <Box width={1.75} />
            {/* <Icon
            iconPath={mdiPlus}
            scale={1.25}
            onClick={() =>
              pushPage(CreateTankDialog, { client: props.client })
            }
          /> */}
          </Box>
        </Row>
        <Column padBetween={1}>
          <For
            each={relatedDeliveries.value}
            fallback={<Txt hint>No deliveries to this Client.</Txt>}
          >
            {(delivery) => <DeliveryCard delivery={delivery} />}
          </For>
        </Column>
      </Body>
    </Page>
  );
}

// src/views/clients/Client.page.vue
<script setup lang="ts">
import { PropType, watchEffect } from "vue";
import { pageTransitions, popPage } from "@/Nav";
import { mdColors } from "@/miwi-md/Box/BoxDecoration";
import { Client } from "@/AppData";
import { pushPage } from "@/Nav";
import { FuelType, getAppData } from "@/AppData";
import DeleteDialog from "../components/DeleteDialog.vue";
import { orderDocs } from "@/utils";
// const appData = getAppData();

const props = defineProps({
  client: {
    type: Object as PropType<Client>,
    required: true,
  },
});

watchEffect(() => {
  if (props.client.isDeleted) {
    popPage();
  }
});

function deletePressed() {
  pushPage(DeleteDialog, {
    obj: props.client,
    message: `Are you sure you want to permanently delete "${
      props.client.clientId ?? ``
    } ${props.client.clientId && props.client.name ? ` - ` : ``} ${
      props.client.name ?? ``
    }"?`,
  });
}
</script>

<script lang="ts">
export default {
  transitions: pageTransitions.slideUp(),
};
</script>

<template>
  <Page>
    <AppBar
      ><Text title>Edit Client</Text>
      <template #right>
        <SettingsButton />
      </template>
    </AppBar>

    <Body v-if="client.isLoaded">
      <Row
        :sty="{
          width: `1f`,
          alignX: $Align.spaceBetween,
          alignY: $Align.start,
        }"
      >
        <Icon icon="dotsVertical" :color="mdColors.transparent" />
        <Text title>Client Info</Text>
        <DeleteOptionsButton @delete="deletePressed" />
      </Row>
      <Card :sty="{ width: `1f` }">
        <ClientFields
          v-model:name="client.name"
          v-model:clientId="client.clientId"
          v-model:phoneNumber="client.phoneNumber"
          v-model:address="client.address"
          v-model:notes="client.notes"
        />
      </Card>
      <Box />
      <Row
        :sty="{
          width: `1f`,
          align: $Align.spaceBetween,
        }"
      >
        <Box :sty="{ width: 1.75 }" />
        <Text title>Tanks</Text>
        <Box :sty="{ width: 1.75, align: $Align.centerLeft }">
          <Icon icon="plus" :scale="1.25" @click.stop="client.tanks?.add({})" />
        </Box>
      </Row>
      <TankEntry
        v-for="(tank, index) in orderDocs(
          client.tanks ?? [],
          (x) => x.creationTimePosix,
        )"
        :key="index"
        :tank="tank"
        >{{ index + 1 }}</TankEntry
      >
    </Body>
    <Body v-else :sty="{ align: $Align.center }">
      <Text hint>Loading...</Text>
    </Body>
  </Page>
</template>
