// src/views/clients/ClientSearchBar.vue
<script setup lang="ts">
import { defineProps, PropType, defineEmits } from "vue";
import { mdColors } from "@/miwi-md/Box/BoxDecoration";

const props = defineProps({
  filterString: {
    type: String,
    required: true,
  },
  sty: {
    type: Object as PropType<Partial<Sty>>,
    default: {},
  },
});

const emit = defineEmits(["update:filterString", "close"]);
function close() {
  emit("update:filterString", "");
  emit("close");
}
</script>

<template>
  <Row
    :sty="{
      width: `1f`,
      background: mdColors.green,
      pad: 0.75,
      shadowSize: 1.25,
      shadowDirection: $Align.bottomCenter,
      zIndex: 1,
      ...sty,
    }"
  >
    <Row
      :sty="{
        width: `1f`,
        pad: 0.25,
        cornerRadius: 0.75,
        align: $Align.centerLeft,
        background: mdColors.white,
        textColor: mdColors.grey,
      }"
    >
      <Box :sty="{ width: 0.25 }" />
      <Field
        hint="Search by Name or ID"
        :value="filterString"
        :hasFocus="true"
        @update:value="emit(`update:filterString`, $event)"
      />
      <Box :sty="{ width: 0.25 }" />
    </Row>
    <Icon :onClick="close" :scale="1.5" icon="close" :color="mdColors.white" />
    <!-- <Icon
      :onClick="addPressed"
      :scale="1.5"
      icon="plus"
      :color="mdColors.white"
    /> -->
  </Row>
</template>

// src/Clients/ClientSearchBar.tsx
import { Row, Box, Field, Icon, mdColors, Prop, useProp } from "miwi";
import { mdiClose } from "@mdi/js";

export default function ClientSearchBar(props: {
  filterString: Prop<string>;
  isSearching: Prop<boolean>;
}) {
  
  function close() {
    props.filterString.value = ``;
    props.isSearching.value = false;
  }

  return (
    <Row
      widthGrows={true}
      fill={$theme.colors.primary}
      padBetween={0.75}
      zIndex={1}
    >
      <Row
        widthGrows={true}
        pad={0.25}
        cornerRadius={0.75} //0.75
        align={$Align.centerLeft}
        fill={mdColors.white}
        stroke={mdColors.grey}
      >
        <Box width={0.25} />
        <Field
          hintText={"Search by Name or ID"}
          scale={1}
          fill={mdColors.white}
          widthGrows={true}
          hasFocus={useProp(true)} // Check if this is correct !!!
          value={props.filterString}
        />
        <Box width={0.25} />
      </Row>
      <Icon
        iconPath={mdiClose}
        stroke={mdColors.white}
        onClick={close}
        scale={1.35}
      />
    </Row>
  );
}
